services:

  postgres:
    image: postgres
    container_name: vsv-shop-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5zm7aa8o
      PGDATA: /data/postgres
      POSTGRES_DB: vsv
    volumes:
      - postgres:/data/postgres
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    networks:
      - default


  redis:
    image: redis:latest
    container_name: vsv-shop-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=5zm7aa8o
      - REDIS_PORT=6379
    networks:
      - default

networks:
  default:
    name: vsv-shop

volumes:
  postgres:

# docker compose up -d --build