spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: jdbc:postgresql://localhost:5432/vsv?createDatabaseIfNotExist=true
    username: postgres
    password: 5zm7aa8o
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: bangtranvan08@gmail.com
#    password: inztsmgbywgzmevn


environment:
  info: develop_environment

# application-dev.yml
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: vsv-shop
    server: http://localhost:${server.port}
    title: VSV SHOP API
    version: 1.0.0
app:
  jwt:
    secret: d23507c6beedda00c5c65a1f0edfafea5adbbcbaa3a6225213542cfb16a914f6
    expiration-milliseconds: 3600000
    refresh-expiration-milliseconds: 604800000
  redis:
    port: 6379
    host: localhost
    password: 5zm7aa8o