server:
  port: 8080

spring:
  application:
    name: vsv-shop
  profiles:
    active: @spring.profiles.active@
  devtools:
    restart:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: info
    web: info


payment:
  vnpay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: DD7EOCBJ
    secretKey: W6R0XYAF795RNFJMZYR73BK9S8RIZVB6
    returnUrl: http://localhost:8080/api/payments/vnpay-callback
    version: 2.1.0
    command: pay
    orderType: other