server:
  port: 8080

spring:
  application:
    name: vsv-shop
  profiles:
    active: @spring.profiles.active@
  devtools:
    restart:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: info
    web: info