spring:
  config:
    activate:
      on-profile: test
  devtools:
    add-properties: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

environment:
  info: test_environment

# application-test.yml
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: vsv-shop
    server: ${VSV_SHOP:http://localhost:${server.port}}
    title: VSV SHOP API
    version: 1.0.0
